#CONFIG_ZMK_KEYBOARD_NAME="My_Macropad"

CONFIG_USB_DEVICE_VID=0x1D50
CONFIG_USB_DEVICE_PID=0xCAFE
CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y  # 如果需要蓝牙


# 启用GPIO LED驱动（用PWM就改成CONFIG_PWM_LEDS=y）
CONFIG_GPIO_LEDS=y



# 基础电量检测
#CONFIG_ZMK_BATTERY=y
#CONFIG_ZMK_BATTERY_REPORTING=y

# 电量上报间隔（秒），默认 60 秒，可改成 30 秒更灵敏
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=10

# 必需：启用电池电压检测支持
CONFIG_ZMK_BATTERY=y
# 必需：ADC驱动（nice!nano/nRF52840）
CONFIG_ADC=y
# 推荐：启用电池电量报告（通过蓝牙发送电量到主机）
CONFIG_ZMK_BATTERY_REPORTING=y
# 可选：启用蓝牙电池服务（在Windows/macOS状态栏显示电量图标）
CONFIG_BT_BAS=y
